# Added sample SCRIPT For CREATE UER
---
- name: this playbook is to create user
  hosts: all
  become: true
  tasks:
  - name: creating user tom
    user: 
      name: tom  #This playbook is used to create TOM USer
